spring:
  config:
    activate:
      on-profile: local
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB

  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password: 1111
    driver-class-name: org.h2.Driver
  devtools:
    livereload:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /**

jwt:
  secret: ${JWT_SECRET_KEY}

feign:
  client:
    config:
      apple-public-key-client:
        connect-timeout: 5000
        read-timeout: 3000

oauth:
  apple:
    iss: https://appleid.apple.com
    client-id: ${APPLE_CLIENT_ID}
    nonce: ${APPLE_NONCE}

#security:
#  oauth2:
#    client:
#      registration:
#        apple:
#          grant-type: authorization_code
#          client-id: ${APPLE_CLIENT_ID}
#          key-id: ${APPLE_KEY_ID}
#          team-id: ${APPLE_TEAM_ID}
#          key-path: ${APPLE_KEY_PATH}
#          redirect-uri: ${APPLE_REDIRECT_URI}
#          client-authentication-method: POST
#          client-name: Apple
#          scope:
#            - email
#            - name
#      provider: #사용자 인증 정보를 제공하는 구성 요소를 지정하는데 사용
#        apple:
#          authorizationUri: https://appleid.apple.com/auth/authorize?response_mode=form_post #인가코드  uri
#          tokenUri: https://appleid.apple.com/auth/token #id_token uri


